from enum import Enum

class EventType(Enum):
    UNKNOWN = "UNKNOWN"
    NONE = "none"
    FIRE_BULLET = "fire_bullets"
    WEAPON_FIRE = "weapon_fire"
    WEAPON_RELOAD = "weapon_reload"
    WEAPON_ZOOM = "weapon_zoom"
    ITEM_PURCHASE = "item_purchase"
    ITEM_EQUIP = "item_equip"
    ITEM_PICKUP = "item_pickup"
    BUYTIME_ENDED = "buytime_ended"
    BULLET_DAMAGE = "bullet_damage"
    ROUND_FREEZE_END = "round_freeze_end"
    BOMB_EXPLODED = "bomb_exploded"
    BOMB_BEGINPLANT = "bomb_beginplant"
    BOMB_BEGINDEFUSE = "bomb_begindefuse"
    BOMB_PICKUP = "bomb_pickup"
    BOMB_DROPPED = "bomb_dropped"
    BOMB_PLANTED = "bomb_planted"
    BEGIN_NEW_MATCH = "begin_new_match"
    RANK_UPDATE = "rank_update"
    ROUND_START = "round_start"
    ROUND_END = "round_end"
    PLAYER_BULLET_HIT = "player_bullet_hit"
    PLAYER_TEAM = "player_team"
    PLAYER_HURT = "player_hurt"
    PLAYER_DEATH = "player_death"
    PLAYER_BLIND = "player_blind"
    FLASHBANG_DETONATE = "flashbang_detonate"
    OTHER_DEATH = "other_death"
    INFERNO_EXPIRE = "inferno_expire"
    INFERNO_STARTBURN = "inferno_startburn"
    SMOKEGRENADE_DETONATE = "smokegrenade_detonate"
    SMOKEGRENADE_EXPIRE = "smokegrenade_expired"
    HE_GRENADE_DETONATE = "hegrenade_detonate"
